### ISSUE TITLE
colorSwitchOn is not working

### ISSUE THREAD

**Issue by Malikkhoja-zz** [Haskkor/react-native-switches#5]
Hi,

We have been using this library for a quite a while now and didnt faced any issues. However in last 2 versions, the colorSwitchOn prop isnt taking the color particularly in pill shape

Can anyone help, please

**Comment by jeremy-farnault** [comment]
Hi!

Sorry for the delay. 
I'm not experiencing the same issue unfortunately, I'll investigate more.

Cheers,
Jeremy

**Comment by jeremy-farnault** [comment]
Hi,

It's super late but I didn't have time to work on it before. Sorry.
It's fixed now.
