### ISSUE TITLE
Missing Align Attribute for Switch Text

### ISSUE THREAD

**Issue by joerecra** [Haskkor/react-native-switches#6]
There is not an option to align text to center. It's a trouble because my text is more longer than ON/OFF, I have "ON SERVICE/OFFSERVICE" and text on is left is not showing as it should be, you can see it in the attached imaged. 

![4f9f3086-cea0-4a6b-8ab2-158a254b0594](https://user-images.githubusercontent.com/11606218/77245602-bb2e0d00-6bed-11ea-84e4-4e0bfb71462b.jpeg)

Another thing, is there an option to update the width of switch with the width of screen, I mean like percent: 80% for example.

**Comment by jeremy-farnault** [comment]
Hi, 

I won't have time to work on those improvements for a while so feel free to create a PR :) 

Cheers,
Jeremy
